sudo: required
services:
  - docker

before_install:
  - docker build -t etaylorm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run etaylorm/react-test npm test -- --coverage

after_success:
  - docker build -t etaylorm/multi-client ./client
  - docker build -t etaylorm/multi-nginx ./nginx
  - docker build -t etaylorm/multi-server ./server
  - docker build -t etaylorm/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hug
  - docker push etaylorm/multi-client
  - docker push etaylorm/multi-nginx
  - docker push etaylorm/multi-server
  - docker push etaylorm/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ca-central-1-136296178528
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY